# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "tf-production-us-west-2-388372205874"
    dynamodb_table = "tf-lock-production"
    encrypt        = true
    key            = "cosmos/production/default-vpc/388372205874/us-west-2/terraform.tfstate"
    region         = "us-west-2"
  }
}
