# yamllint disable-file
cf_api_token: ENC[AES256_GCM,data:itcBTrtieXxhpVzEJvvTvCBTS+P3FV1hPBbbaHMyZkFIbamM+c9Plg==,iv:FaCdJX5u7uA1xOy8rTfw2nR9+5F/3ZYPkZBTI+bJQuA=,tag:EZ38ZAsTy6c4R7qD/20sCw==,type:str]
cf_zone_id: ENC[AES256_GCM,data:GgZAV9X7V88MavgcwFLF7OLwlcMuERh8FqdM3HezqDI=,iv:L31vuG3EvIMRVN/C+pq4R1y1adPDG4Bp8qnCaDqRAIU=,tag:nXl4orV+tuunFmoeZY35+Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jh3xgndxr62gslph0l6evu7ayt6f4uyxdmnmr3x98z33zrpka4gqglaw8d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3QlR5VVBPeHBrS2F0UmFT
            S2huQ1FzMFpXVXl5c2NoNTNxbHEyR01aNm1ZCnVXNDFKRGtBcWRZTzV6THhqcnlL
            V3p1bTNKekJCL09oSFh6Y09QQjVRT2cKLS0tIDYvWWNIMmRjOUFxcXVSYi95dzRp
            OWhKdStSbjFIQ3FqWDNIdnhmaDVWMUkKfoDrGyZE8oQiu5Mb+v706G1D4+xK6k64
            rpv0yVDDOmGJg1ctXk7znxAE0UPqbU+dHK89yvCEjykFNMrLFNC2nA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-26T03:03:41Z"
    mac: ENC[AES256_GCM,data:QrgzxDPQzf53BWmVeo9HQttTNDHma6AKcAivROF/yIcHtCFJMpH5fpVJa/ftraEqalged1EktiSixEvCDGhH1WF8/vQE3bdkrtcMK+T/qKCKVD5VN8Pz/HxoKASnhl+Z5EnuA6rJN/+4gisp1miiQZ1LPghNFhhUdI9PkwC63xA=,iv:bbftB9ckItFy9QyJ6ztq7Hhu29Vt3BFW5HwuWkWgMn4=,tag:rn0nAXuxoHkuAidAHTuZGg==,type:str]
    pgp: []
    encrypted_regex: ^(cf_api_token|cf_zone_id)$
    version: 3.7.3
