# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "terraform-development-us-west-2-388372205874"
    dynamodb_table = "terraform-lock-development"
    encrypt        = true
    key            = "cosmos/vpc/388372205874/us-west-2/terraform.tfstate"
    region         = "us-west-2"
  }
}
