---
- name: Configure all machines
  hosts: all
  gather_facts: true
  become: true
  roles:
    - common

- name: Configure raspi machines mounted in UCTRONICS Pi Rack Pro
  hosts: pirack
  gather_facts: true
  become: true
  roles:
    - pirack

- name: Setup Cloudflare DDNS service
  hosts: dnsserver
  gather_facts: true
  become: true
  vars_prompt:
    - name: cf_api_token
      prompt: Enter Cloudflare API Token
    - name: cf_zone_id
      prompt: Enter Cloudflare Zone ID
  roles:
    - cf_ddns
