---
- name: Configure all machines
  hosts: all
  gather_facts: true
  become: true
  roles:
    - common

- name: Configure raspi machines mounted in UCTRONICS Pi Rack Pro
  hosts: pirack
  gather_facts: true
  become: true
  roles:
    - pirack
