---
- name: Install Docker Playbook
  hosts: all
  become: yes
  vars:
    container_count: 4
    default_container_name: docker
    default_container_image: ubuntu
    default_container_command: sleep 1
  tasks:
    - name: Add Docker GPG apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        state: present

    - name: Update apt repository cache
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600

    - name: Update apt and install docker-ce/compose
      apt:
        pkg:
          - docker-ce
          - docker-compose-plugin
        state: latest
        update_cache: yes

    - name: Install Docker Module for Python
      pip:
        name: docker
