---
# Startup Automatically
- name: Create systemd service file for Octoprint
  ansible.builtin.copy:
    dest: /etc/systemd/system/octoprint.service
    content: |
      [Unit]
      Description=Octoprint server
      After=network.target

      [Service]
      Type=simple
      User={{ ansible_user }}
      ExecStart={{ octoprint_path }}/venv/bin/octoprint serve
      Restart=always
      Environment=HOME=/home/{{ ansible_user }}/.octoprint

      [Install]
      WantedBy=multi-user.target
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd to apply new service
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable Octoprint service
  ansible.builtin.systemd:
    name: octoprint
    enabled: true

- name: Start Octoprint service
  ansible.builtin.systemd:
    name: octoprint
    state: started

# Install / Setup webcam
- name: Clone mjpg-streamer repository
  ansible.builtin.git:
    repo: 'https://github.com/jacksonliam/mjpg-streamer.git'
    dest: "/home/{{ ansible_user }}/mjpg-streamer"
    version: 'master'
  register: git_clone
  changed_when: git_clone == 0

- name: Change directory, set LD_LIBRARY_PATH, and run make
  ansible.builtin.shell: |
    export LD_LIBRARY_PATH=.
    make
  args:
    chdir: "/home/{{ ansible_user }}/mjpg-streamer/mjpg-streamer-experimental"
    executable: /bin/bash
  environment:
    LD_LIBRARY_PATH: "."
  changed_when: git_clone == 0
