---
- name: Initialize hardware
  hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
    - raspberrypi
    - pirack

- name: Prepare k3s nodes
  hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
    - prereq
    - download

# - name: Initialize cluster on "bootstrap" server node
#   hosts: bootstrap_server
#   gather_facts: true
#   become: true
#   roles:
#     - cluster_init

- name: Initialize and join the remaining server nodes to the cluster
  hosts: servers
  gather_facts: true
  become: true
  roles:
    - server

- name: Initialize and join agent nodes to the cluster
  hosts: agents
  gather_facts: true
  become: true
  roles:
    - agent
