---
- name: Set the timezone
  community.general.timezone:
    name: "{{ system_timezone }}"
  when: (system_timezone is defined)

- name: Install apt packages
  ansible.builtin.apt:
    name:
      - build-essential
      - cmake
      - ffmpeg
      - git
      - imagemagick
      - libffi-dev
      - libjpeg8-dev
      - libv4l-dev
      - libyaml-dev
      - python3-dev
      - python3-pip
      - python3-setuptools
      - python3-venv
      - subversion
    state: present
