---
- name: Set the timezone
  community.general.timezone:
    name: "{{ system_timezone }}"
  when: (system_timezone is defined)

- name: Install apt packages
  ansible.builtin.apt:
    name:
      - python3-pip
      - python3-dev
      - python3-setuptools
      - python3-venv
      - git
      - libffi-dev
      - libyaml-dev
      - build-essential
    state: present
