---
- include_vars: vars/secrets.yml

- name: Ensure venv is installed via apt
  ansible.builtin.apt:
    name: python3.10-venv
    state: present
    update_cache: true
  become: true

- name: Clone the Cloudflare DDNS code via git
  ansible.builtin.git:
    repo: "https://github.com/{{ github_account }}/cloudflare-ddns.git"
    dest: "/home/{{ primary_user }}/cloudflare-ddns"
    single_branch: true
    version: "{{ github_branch }}"

- name: Create config file from template
  ansible.builtin.copy:
    remote_src: true
    src: "/home/{{ primary_user }}/cloudflare-ddns/config-example.json"
    dest: "/home/{{ primary_user }}/cloudflare-ddns/config.json"
    mode: "0755"

- name: Add API token to config
  ansible.builtin.replace:
    path: "/home/sonofborge/cloudflare-ddns/config.json"
    regexp: api_token_here
    replace: "{{ cf_api_token }}"

- name: Add Cloudflare Zone ID to config
  ansible.builtin.replace:
    path: "/home/sonofborge/cloudflare-ddns/config.json"
    regexp: zone_id_here
    replace: "{{ cf_zone_id }}"

- name: Create cron job entry that runs start-sync.sh"
  ansible.builtin.cron:
    name: "Sync IP updates to Cloudflare"
    minute: "*/15" # 15th minute
    job: "/home/{{ primary_user }}/cloudflare-ddns/start-sync.sh"
