---
- name: Ensure Octopath directory exists
  ansible.builtin.file:
    path: "{{ octoprint_path }}"
    state: directory
    mode: '0755'

- name: Ensure virtualenv is installed
  ansible.builtin.pip:
    name: virtualenv
    state: present

- name: Create a virtualenv
  ansible.builtin.command:
    cmd: virtualenv venv
    chdir: "{{ octoprint_path }}"
    creates: "{{ octoprint_path }}/venv/bin/activate"
  register: venv_created
  changed_when: venv_created.rc == 0

- name: Check which Python is being used
  ansible.builtin.command:
    cmd: "{{ octoprint_path }}/venv/bin/python -c 'import sys; print(sys.executable)'"
    chdir: "{{ octoprint_path }}"
  register: python_exec
  changed_when: false

- name: Upgrade pip and install Octoprint within the virtualenv
  ansible.builtin.shell: |
    source "{{ octoprint_path }}"/venv/bin/activate
    pip install --upgrade pip
    pip install https://get.octoprint.org/latest
  args:
    chdir: "{{ octoprint_path }}"
    executable: /bin/bash
  changed_when: venv_created.rc == 0

- name: Add user to groups
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups:
      - tty
      - dialout
    append: true
  become: true
