---
- name: Initialize hardware
  hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
    - raspberrypi
    - pirack

- name: Prepare k3s nodes
  hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
    - prereq
    - download

- name: Prepare k3s servers
  hosts: server
  gather_facts: true
  become: true
  roles:
    - server

- name: Prepare k3s agents
  hosts: agent
  gather_facts: true
  become: true
  roles:
    - agent
