---
all:
  hosts:
    kpimaster:
      ansible_host: 10.40.40.42
    kpinode1:
      ansible_host: 10.40.40.43
    kpinode2:
      ansible_host: 10.40.40.44
    kpinode3:
      ansible_host: 10.40.40.45

  children:
    # All Raspberry Pi host machines
    raspis:
      hosts:
        kpimaster:
        kpinode1:
        kpinode2:
        kpinode3:
    # Raspberry Pi host machines mounted in the UCTRONICS Pi Rack Pro
    pirack:
      hosts:
        kpimaster:
        kpinode1:
        kpinode2:
        kpinode3:

  vars:
    ansible_user: sonofborge
