---
- name: Enable gpio, i2c, and set baudrate
  ansible.builtin.blockinfile:
    path: /boot/firmware/config.txt
    content: |
      dtoverlay=gpio-shutdown
      dtoverlay=gpio_pin=4
      dtoverlay=active_low=1
      dtoverlay=gpio_pull=up
      dtparam=i2c_arm_baudrate=400000
    state: present
    insertafter: EOF

- name: Ensure i2c packages are installed
  ansible.builtin.apt:
    name:
      - python3-pip
      - python3-dev
      - python3-pil
      - python3-setuptools
      - python3-rpi.gpio
      - i2c-tools
    state: present
    update_cache: true
  become: true

- name: Add primary user to i2c group
  ansible.builtin.user:
    name: "{{ primary_user }}"
    group: i2c

- name: Clone the UCTRONICS Pi Rack Pro code via git
  ansible.builtin.git:
    repo: "https://github.com/{{ github_account }}/SKU_RM0004.git"
    dest: "/home/{{ primary_user }}/SKU_RM0004"
    single_branch: true
    version: main

- name: Create rc.local file and enable display script on system start
  ansible.builtin.copy:
    dest: /etc/rc.local
    content: |
      #!/bin/sh -e
      cd "/home/{{ primary_user }}/SKU_RM0004"
      make clean
      make
      ./display &
    mode: a+x

- name: Make sure rc.local is started (and run on system start)
  ansible.builtin.systemd:
    state: started
    name: rc-local
    enabled: true
