---
- name: Manage Users Playbook
  hosts: all
  become: yes
  tasks:
    - name: Make sure we have a 'wheel' group
      group:
        name: wheel
        state: present

    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Create xsob user
      ansible.builtin.user:
        name: xsob
        password: "{{ user_password | password_hash('sha512', user_salt) }}"
        state: present
        update_password: on_create

    - name: Add sudoers users to wheel group
      user:
        name: xsob
        groups: wheel
        append: yes
        state: present
        createhome: yes

    - name: Lock/Disable default image-build user
      ansible.builtin.user:
        name: ephemeral
        state: present
        password_lock: yes
        shell: "/sbin/nologin"
