---
k3s_version: v1.27.4+k3s1
ansible_user: sonofborge
systemd_dir: /etc/systemd/system
system_timezone: "UTC"
server_ip: "{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}"
extra_server_args: ""
extra_agent_args: ""
