---
k3s_version: v1.27.4+k3s1
ansible_user: sonofborge
systemd_dir: /etc/systemd/system
system_timezone: "UTC"
server_ip: "{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}"

flannel_iface: "eth0"
k3s_node_ip: "{{ ansible_facts[flannel_iface]['ipv4']['address'] }}"

extra_args: >-
  --flannel-iface={{ flannel_iface }}
  --node-ip={{ k3s_node_ip }}

extra_server_args: >-
  {{ extra_args }}
  --node-taint node-role.kubernetes.io/control-plane=true:NoSchedule
extra_agent_args: >-
  {{ extra_args }}
